// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSzHf-dgjlMPus3AavCujJS0xpi15MKw',
    appId: '1:48359423210:web:a44fcf63581bd283846b93',
    messagingSenderId: '48359423210',
    projectId: 'cleango-pmob',
    authDomain: 'cleango-pmob.firebaseapp.com',
    databaseURL: 'https://cleango-pmob-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cleango-pmob.firebasestorage.app',
    measurementId: 'G-HEHYQVKZ5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvZgpicPkMWFiApjhtbeA5o61RNjxmyt4',
    appId: '1:48359423210:android:dcb55b805d51e440846b93',
    messagingSenderId: '48359423210',
    projectId: 'cleango-pmob',
    databaseURL: 'https://cleango-pmob-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cleango-pmob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HJLiyBV6IV4QmTtlFb-riI5G8ihdfy8',
    appId: '1:48359423210:ios:b484f5cbc2bb5286846b93',
    messagingSenderId: '48359423210',
    projectId: 'cleango-pmob',
    databaseURL: 'https://cleango-pmob-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cleango-pmob.firebasestorage.app',
    iosBundleId: 'com.example.cleango',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HJLiyBV6IV4QmTtlFb-riI5G8ihdfy8',
    appId: '1:48359423210:ios:b484f5cbc2bb5286846b93',
    messagingSenderId: '48359423210',
    projectId: 'cleango-pmob',
    databaseURL: 'https://cleango-pmob-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cleango-pmob.firebasestorage.app',
    iosBundleId: 'com.example.cleango',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfSzHf-dgjlMPus3AavCujJS0xpi15MKw',
    appId: '1:48359423210:web:ef1b18ec8fcda2be846b93',
    messagingSenderId: '48359423210',
    projectId: 'cleango-pmob',
    authDomain: 'cleango-pmob.firebaseapp.com',
    databaseURL: 'https://cleango-pmob-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cleango-pmob.firebasestorage.app',
    measurementId: 'G-588LFX97Y4',
  );
}
